spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2

  datasource:
    url: jdbc:h2:file:./gl;MODE=MYSQL
    usename: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2

#  datasource:
#    url: jdbc:mysql://digipay@10.198.111.61:3306/general_ledger_db?characterEncoding=utf8
#    usename: digipay
#    password: D1giP@y_Us3r_MNG
#    #driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.mysql.cj.jdbc.MysqlDataSource

#    schema: schema-h2.sql
#    data: data-h2.sql
#    continue-on-error: true

