package dp.gl.gltemplatesimulator.swing.panel;

import dp.gl.gltemplatesimulator.dto.TemplateDTO;

import javax.swing.*;
import java.awt.*;

public class TemplateAndEventEditPanel {
    private JPanel rootPanel;
    private JTabbedPane tabbedPane1;
    private JTextArea txtVoucherTypeFormula;
    private JTextArea txtVoucherDescription;
    private JTextArea txtJSON;
    private TemplateEditPanel templateEditPanel;

    TemplateDTO templateDTO = new TemplateDTO();

    public TemplateDTO getTemplateDTO() {


        return templateDTO;
    }

    public void setTemplateDTO(TemplateDTO templateDTO) {
        this.templateDTO = templateDTO;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        templateEditPanel = new TemplateEditPanel();
        rootPanel.add(templateEditPanel.$$$getRootComponent$$$(), BorderLayout.CENTER);
        tabbedPane1 = new JTabbedPane();
        rootPanel.add(tabbedPane1, BorderLayout.SOUTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        tabbedPane1.addTab("ورودی JSON", scrollPane1);
        txtJSON = new JTextArea();
        scrollPane1.setViewportView(txtJSON);
        final JScrollPane scrollPane2 = new JScrollPane();
        tabbedPane1.addTab("VoucherType", scrollPane2);
        txtVoucherTypeFormula = new JTextArea();
        scrollPane2.setViewportView(txtVoucherTypeFormula);
        final JScrollPane scrollPane3 = new JScrollPane();
        tabbedPane1.addTab("VoucherDescription", scrollPane3);
        txtVoucherDescription = new JTextArea();
        scrollPane3.setViewportView(txtVoucherDescription);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
