package dp.gl.gltemplatesimulator.swing.panel;

import dp.gl.gltemplatesimulator.model.Template;
import dp.gl.gltemplatesimulator.util.NVL;

import javax.swing.*;
import java.awt.*;

public class TemplateEditPanel extends JPanel {
    private JPanel rootPanel;
    private JTabbedPane tabbedPane1;

    private JTextField txtName;
    private JTextField txtF_event;
    private JTextField txtF_account_base;
    private JTextField txtOrderno;
    private JCheckBox chkStatus;
    private JTextArea txtStatus_formula;
    private JTextArea txtAccount_no_formula;
    private JTextArea txtDebit_formula;
    private JTextArea txtCredit_formula;
    private JTextArea txtDescription_formula;
    private JTextArea txtCostcenter1_formula;
    private JTextArea txtCostcenter2_formula;
    private JTextArea txtCostcenter3_formula;

    private Template template = new Template();

    public Template getTemplate() {
        template.setName(txtName.getText());
        template.setF_event(NVL.getInt(txtF_event.getText()));
        template.setF_account_base(NVL.getInt(txtF_account_base.getText()));
        template.setOrder_no(NVL.getInt(txtOrderno.getText()));
        template.setStatus(chkStatus.isSelected() ? 1 : 0);
        template.setStatus_formula(txtStatus_formula.getText());
        template.setAccount_no_formula(txtAccount_no_formula.getText());
        template.setDebit_formula(txtDebit_formula.getText());
        template.setCredit_formula(txtCredit_formula.getText());
        template.setDescription_formula(txtDescription_formula.getText());
        template.setCostcenter1_formula(txtCostcenter1_formula.getText());
        template.setCostcenter2_formula(txtCostcenter2_formula.getText());
        template.setCostcenter3_formula(txtCostcenter3_formula.getText());
//        template.setVersion(NVL.getInt(template.getVersion())+1);
//        template.set(txt.getText());
//        template.set(txt.getText());
        return template;
    }

    public void setTemplate(Template template) {
        this.template = template;
        txtName.setText(template.getName());
        txtF_event.setText(NVL.getString(template.getF_event()));
        txtF_account_base.setText(NVL.getString(template.getF_account_base()));
        txtOrderno.setText(NVL.getString(template.getOrder_no()));
        chkStatus.setSelected(NVL.getInt(template.getStatus()) > 0 ? true : false);
        txtStatus_formula.setText(template.getStatus_formula());
        txtAccount_no_formula.setText(template.getAccount_no_formula());
        txtDebit_formula.setText(template.getDebit_formula());
        txtCredit_formula.setText(template.getCredit_formula());
        txtDescription_formula.setText(template.getDescription_formula());
        txtCostcenter1_formula.setText(template.getCostcenter1_formula());
        txtCostcenter2_formula.setText(template.getCostcenter2_formula());
        txtCostcenter3_formula.setText(template.getCostcenter3_formula());
    }

    public TemplateEditPanel() {
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 0, 0));
        rootPanel.add(panel1, BorderLayout.SOUTH);
        chkStatus = new JCheckBox();
        chkStatus.setText("status");
        panel1.add(chkStatus);
        txtOrderno = new JTextField();
        txtOrderno.setColumns(5);
        txtOrderno.putClientProperty("caretWidth", new Integer(40));
        panel1.add(txtOrderno);
        final JLabel label1 = new JLabel();
        label1.setText("orderno");
        panel1.add(label1);
        txtF_account_base = new JTextField();
        txtF_account_base.setColumns(5);
        txtF_account_base.putClientProperty("caretWidth", new Integer(40));
        panel1.add(txtF_account_base);
        final JLabel label2 = new JLabel();
        label2.setText("f_account_base");
        panel1.add(label2);
        txtF_event = new JTextField();
        txtF_event.setColumns(5);
        txtF_event.putClientProperty("caretWidth", new Integer(40));
        panel1.add(txtF_event);
        final JLabel label3 = new JLabel();
        label3.setText("f_event");
        panel1.add(label3);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        rootPanel.add(panel2, BorderLayout.NORTH);
        txtName = new JTextField();
        panel2.add(txtName, BorderLayout.CENTER);
        final JLabel label4 = new JLabel();
        label4.setText("name");
        panel2.add(label4, BorderLayout.EAST);
        tabbedPane1 = new JTabbedPane();
        tabbedPane1.setTabLayoutPolicy(0);
        tabbedPane1.setTabPlacement(1);
        rootPanel.add(tabbedPane1, BorderLayout.CENTER);
        final JScrollPane scrollPane1 = new JScrollPane();
        tabbedPane1.addTab("status", scrollPane1);
        txtStatus_formula = new JTextArea();
        scrollPane1.setViewportView(txtStatus_formula);
        final JScrollPane scrollPane2 = new JScrollPane();
        tabbedPane1.addTab("account_no", scrollPane2);
        txtAccount_no_formula = new JTextArea();
        scrollPane2.setViewportView(txtAccount_no_formula);
        final JScrollPane scrollPane3 = new JScrollPane();
        tabbedPane1.addTab("debit", scrollPane3);
        txtDebit_formula = new JTextArea();
        scrollPane3.setViewportView(txtDebit_formula);
        final JScrollPane scrollPane4 = new JScrollPane();
        tabbedPane1.addTab("credit", scrollPane4);
        txtCredit_formula = new JTextArea();
        scrollPane4.setViewportView(txtCredit_formula);
        final JScrollPane scrollPane5 = new JScrollPane();
        tabbedPane1.addTab("description", scrollPane5);
        txtDescription_formula = new JTextArea();
        scrollPane5.setViewportView(txtDescription_formula);
        final JScrollPane scrollPane6 = new JScrollPane();
        tabbedPane1.addTab("costcenter1", scrollPane6);
        txtCostcenter1_formula = new JTextArea();
        scrollPane6.setViewportView(txtCostcenter1_formula);
        final JScrollPane scrollPane7 = new JScrollPane();
        tabbedPane1.addTab("cc2", scrollPane7);
        txtCostcenter2_formula = new JTextArea();
        scrollPane7.setViewportView(txtCostcenter2_formula);
        final JScrollPane scrollPane8 = new JScrollPane();
        tabbedPane1.addTab("cc3", scrollPane8);
        txtCostcenter3_formula = new JTextArea();
        scrollPane8.setViewportView(txtCostcenter3_formula);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
